"""
Django settings for brfn project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import parse_qs, urlparse
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n(#(u7o^*u#74(gp**zy&t@-=psymeg9bl2#p=^(s@%b0w$yid"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1",
).split(",")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

# Allow Render deployment hostname automatically when available.
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "users",
    "products",
    "orders",
    "sustainability",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "users.middleware.SessionTimeoutMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "brfn.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "brfn.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def parse_database_url(database_url: str):
    parsed = urlparse(database_url)
    scheme = parsed.scheme
    if scheme in {"postgres", "postgresql"}:
        engine = "django.db.backends.postgresql"
    elif scheme in {"mysql"}:
        engine = "django.db.backends.mysql"
    elif scheme in {"sqlite"}:
        engine = "django.db.backends.sqlite3"
    else:
        raise ValueError(f"Unsupported database scheme: {scheme}")

    if engine == "django.db.backends.sqlite3":
        db_path = parsed.path
        if db_path.startswith("/"):
            db_path = db_path[1:]
        return {
            "ENGINE": engine,
            "NAME": BASE_DIR / db_path,
        }

    query_params = parse_qs(parsed.query)
    options = {}
    if "sslmode" in query_params:
        options["sslmode"] = query_params["sslmode"][-1]

    return {
        "ENGINE": engine,
        "NAME": parsed.path[1:],
        "USER": parsed.username or "",
        "PASSWORD": parsed.password or "",
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
        "OPTIONS": options,
    }

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///db.sqlite3")
DATABASES = {
    "default": parse_database_url(DATABASE_URL)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Remote quality-classification model server
QUALITY_MODEL_API_URL = os.getenv("QUALITY_MODEL_API_URL", "")
QUALITY_MODEL_API_KEY = os.getenv("QUALITY_MODEL_API_KEY", "")
QUALITY_MODEL_AUTH_HEADER = os.getenv("QUALITY_MODEL_AUTH_HEADER", "X-API-Key")
QUALITY_MODEL_API_TIMEOUT_SECONDS = int(os.getenv("QUALITY_MODEL_API_TIMEOUT_SECONDS", "45"))

# Remote recommendation model server
RECOMMENDATION_API_URL = os.getenv("RECOMMENDATION_API_URL", "")
RECOMMENDATION_API_KEY = os.getenv("RECOMMENDATION_API_KEY", "")
RECOMMENDATION_AUTH_HEADER = os.getenv("RECOMMENDATION_AUTH_HEADER", "X-API-Key")
RECOMMENDATION_API_TIMEOUT_SECONDS = int(os.getenv("RECOMMENDATION_API_TIMEOUT_SECONDS", "20"))

# Stripe payments (demo/test defaults)
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
STRIPE_API_VERSION = os.getenv("STRIPE_API_VERSION", "2024-11-20.acacia")
STRIPE_CHECKOUT_CURRENCY = os.getenv("STRIPE_CHECKOUT_CURRENCY", "usd")
STRIPE_CHECKOUT_DEMO_CARD_ONLY = os.getenv("STRIPE_CHECKOUT_DEMO_CARD_ONLY", "1").lower() in {"1", "true", "yes", "on"}
STRIPE_CHECKOUT_PAYMENT_METHOD_TYPES = os.getenv("STRIPE_CHECKOUT_PAYMENT_METHOD_TYPES", "card").split(",")
STRIPE_WEBHOOK_MAX_BODY_BYTES = int(os.getenv("STRIPE_WEBHOOK_MAX_BODY_BYTES", "1048576"))

# Session security
SESSION_IDLE_TIMEOUT_SECONDS = int(os.getenv("SESSION_IDLE_TIMEOUT_SECONDS", "1800"))
