from django.urls import path
from .views_frontend import (
    product_list,
    product_detail,
    producer_list_view,
    login_view,
    register_view,
    profile_view,
    ai_insights_view,
    for_you_recommendations_view,
    logout_view,
    cart_view,
    update_cart_item,
    remove_cart_item,
    checkout_view,
    add_to_cart,
    producer_add_product,
    producer_manage_products,
    producer_quality_inspection_view,
    producer_edit_product,
    producer_delete_product,
    order_list_view,
    order_detail_view,
    producer_order_list_view,
    producer_confirm_order_view,
    producer_ship_order_view,
    customer_confirm_delivery_view,
    reorder_order,
    submit_review_view,
    producer_review_moderation_view,
    producer_review_action_view,
    recurring_order_list_view,
    create_recurring_from_order_view,
    recurring_order_edit_view,
    recurring_order_generate_now_view,
    recurring_order_delete_view,
    content_list_view,
    content_detail_view,
    producer_content_list_view,
    producer_content_create_view,
    producer_content_edit_view,
    producer_content_delete_view,
    sustainability_report_view,
    manager_ai_control_center_view,
    financial_reports_view,
    financial_reports_export_csv_view,
    financial_reports_export_pdf_view,
    admin_producer_payouts_view,
    admin_pay_producer_view,
    producer_balance_view,
)

urlpatterns = [
    path("products/", product_list, name="product_list"),
    path("producers/", producer_list_view, name="producer_list"),
    path("products/<int:pk>/", product_detail, name="product_detail"),
    path("products/<int:pk>/add/", add_to_cart, name="add_to_cart"),
    path("content/", content_list_view, name="content_list"),
    path("sustainability/report/", sustainability_report_view, name="sustainability_report"),
    path("manager/ai-control-center/", manager_ai_control_center_view, name="manager_ai_control_center"),
    path("manager/financial-reports/", financial_reports_view, name="financial_reports"),
    path("manager/financial-reports/export/csv/", financial_reports_export_csv_view, name="financial_reports_export_csv"),
    path("manager/financial-reports/export/pdf/", financial_reports_export_pdf_view, name="financial_reports_export_pdf"),
    path("manager/producer-payouts/", admin_producer_payouts_view, name="admin_producer_payouts"),
    path("manager/producer-payouts/<int:producer_id>/pay/", admin_pay_producer_view, name="admin_pay_producer"),
    path("content/<slug:slug>/", content_detail_view, name="content_detail"),
    path("login/", login_view, name="login"),
    path("register/", register_view, name="register"),
    path("profile/", profile_view, name="profile"),
    path("ai/insights/", ai_insights_view, name="ai_insights"),
    path("recommendations/for-you/", for_you_recommendations_view, name="for_you_recommendations"),
    path("logout/", logout_view, name="logout"),
    path("cart/", cart_view, name="cart"),
    path("cart/items/<int:item_id>/update/", update_cart_item, name="update_cart_item"),
    path("cart/items/<int:item_id>/remove/", remove_cart_item, name="remove_cart_item"),
    path("checkout/", checkout_view, name="checkout"),
    path("orders/", order_list_view, name="order_list"),
    path("orders/<int:pk>/", order_detail_view, name="order_detail"),
    path("orders/<int:pk>/reorder/", reorder_order, name="reorder_order"),
    path("orders/<int:order_id>/products/<int:product_id>/review/", submit_review_view, name="submit_review"),
    path("recurring-orders/", recurring_order_list_view, name="recurring_order_list"),
    path("recurring-orders/create-from-order/<int:order_id>/", create_recurring_from_order_view, name="create_recurring_from_order"),
    path("recurring-orders/<int:recurring_id>/edit/", recurring_order_edit_view, name="recurring_order_edit"),
    path("recurring-orders/<int:recurring_id>/generate/", recurring_order_generate_now_view, name="recurring_order_generate"),
    path("recurring-orders/<int:recurring_id>/delete/", recurring_order_delete_view, name="recurring_order_delete"),
    path("producer/products/", producer_manage_products, name="producer_manage_products"),
    path("producer/quality-inspection/", producer_quality_inspection_view, name="producer_quality_inspection"),
    path("producer/products/add/", producer_add_product, name="producer_add_product"),
    path("producer/products/<int:pk>/edit/", producer_edit_product, name="producer_edit_product"),
    path("producer/products/<int:pk>/delete/", producer_delete_product, name="producer_delete_product"),
    path("producer/orders/", producer_order_list_view, name="producer_order_list"),
    path("producer/orders/<int:pk>/confirm/", producer_confirm_order_view, name="producer_confirm_order"),
    path("producer/orders/<int:pk>/ship/", producer_ship_order_view, name="producer_ship_order"),
    path("producer/balance/", producer_balance_view, name="producer_balance"),
    path("producer/reviews/", producer_review_moderation_view, name="producer_review_moderation"),
    path("producer/reviews/<int:review_id>/action/", producer_review_action_view, name="producer_review_action"),
    path("producer/content/", producer_content_list_view, name="producer_content_list"),
    path("producer/content/create/", producer_content_create_view, name="producer_content_create"),
    path("producer/content/<int:post_id>/edit/", producer_content_edit_view, name="producer_content_edit"),
    path("producer/content/<int:post_id>/delete/", producer_content_delete_view, name="producer_content_delete"),
    path("orders/<int:pk>/confirm-delivery/", customer_confirm_delivery_view, name="customer_confirm_delivery"),
]
