# Generated by Django 6.0.3 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_producer_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
