# Generated by Django 6.0.3 on 2026-04-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_delivery_fields"),
        ("products", "0004_product_marketplace_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("frequency", models.CharField(choices=[("weekly", "Weekly"), ("fortnightly", "Fortnightly")], default="weekly", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_date", models.DateField()),
                ("delivery_address", models.CharField(blank=True, max_length=255)),
                ("delivery_postcode", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RecurringOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
                ("recurring_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.recurringorder")),
            ],
        ),
    ]
