# Generated by Django 6.0.3 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_available_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allergen_info",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="availability",
            field=models.CharField(
                choices=[
                    ("in_season", "In Season"),
                    ("year_round", "Available Year-Round"),
                    ("unavailable", "Unavailable"),
                ],
                default="year_round",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="harvest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_organic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="product",
            name="seasonal_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="seasonal_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(default="item", max_length=50),
        ),
    ]
