# Generated by Django 5.2.9 on 2026-04-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_contentpost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inspection_image", models.ImageField(blank=True, upload_to="quality_inspections/")),
                ("produce_type", models.CharField(blank=True, max_length=50)),
                ("freshness_label", models.CharField(choices=[("fresh", "Fresh"), ("rotten", "Rotten"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("freshness_confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("color_score", models.PositiveSmallIntegerField()),
                ("size_score", models.PositiveSmallIntegerField()),
                ("ripeness_score", models.PositiveSmallIntegerField()),
                ("overall_grade", models.CharField(choices=[("A", "Grade A"), ("B", "Grade B"), ("C", "Grade C")], max_length=1)),
                ("suggested_action", models.CharField(blank=True, max_length=255)),
                ("explanation", models.TextField(blank=True)),
                ("assessed_by_model", models.CharField(default="heuristic_quality_pipeline", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quality_inspections", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quality_inspections", to="products.product")),
            ],
        ),
    ]
